user:
  email_max_length: 255
  password_min_length: 6
  name_max_length: 50
  avatar_size: 80
  remember: "1"
  nav_avatar: 55
position:
  min_name: 2
  max_name: 50
  max_short_name: 10
upload:
  max_size: 5
  logo_width: 300
  logo_height: 300
paginate:
  per_page: 10
project:
  min_name: 5
